### ISSUE TITLE
Latest Hearthstone path broke patcher

### ISSUE THREAD

**Issue by AiSatan** [yangyuan/hearthrock#11]
After lastest update patcher was broken, crash happens here:
`var hearthstoneAssembly = AssemblyDefinition.ReadAssembly(hearthstoneAssemblyPath, new ReaderParameters { AssemblyResolver = resolver });`

> System.BadImageFormatException: 'Format of the executable (.exe) or library (.dll) is invalid.'

**Comment by yangyuan** [comment]
Close this because the root of problem should be #13
