### ISSUE TITLE
Decrypt Assembly-CSharp.dll

### ISSUE THREAD

**Issue by yangyuan** [yangyuan/hearthrock#13]
In the recent patches, Assembly-CSharp.dll is no longer a pure dotNET assembly. It seems that the DLL got encrypted (or compiled to native binary), but the DLL still can be recognized by Unity engine.

The developing of the Hearthrock need to add Assembly-CSharp.dll as assembly reference, which means we need to find a way to decrypt the Assembly-CSharp.dll.

If anyone knows how it was encrypted and how to decrypt it, please generously let me know. XD

**Comment by AiSatan** [comment]
I found some interesting stuff in memory, may we can extract it 

![image](https://user-images.githubusercontent.com/2905049/27636769-c7288288-5c15-11e7-9576-31753f7f8c15.png)

**Comment by yangyuan** [comment]
The stuff the left window are parsed dotNET assembly metadata, it should be there because dotNet need them to be there to run the code.

So your screenshot proves that the Assembly-CSharp.dll still contains dotNet assembly, not native code.
Theoretically, we can extract that and generate the corresponding DLL.
But I don't think it's a good idea, I am trying to find out how they load the assembly. It should be easier if we use the same way to extract the assembly.

**Comment by yangyuan** [comment]
It seems that they modified the PE signature of the DLL.
And encrypted the text (assembly) data.

```
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
```
encrypted to
```
0D B7 E7 D6 FF 5A 81 57 0D B7 E7 D6 FF 5A 81 57
```

You can see the repeating `0D B7 E7 D6 FF 5A 81 57`, so maybe it's a very simple shifting encryption or something similar...

**Comment by yangyuan** [comment]
The content after address 609200 looks abnormal, maybe the AES key is there.

**Comment by SimiPro** [comment]
can you mby upload an old version of the Assembly-CSharp.dll ? than i will also take a look at it too.

**Comment by AiSatan** [comment]
I think about some hook on hs Assembly.Load methods, may we will find something.

I have attached old version as .zip

[Assembly-CSharp.zip](https://github.com/yangyuan/hearthrock/files/1124091/Assembly-CSharp.zip)

**Comment by jakibaki** [comment]
The assembly-csharp.dll from the mac version doesn't seem to be encrypted at all (I can at least open and edit it using DNSpy)
![bildschirmfoto 2017-07-05 um 11 49 00](https://user-images.githubusercontent.com/5159436/27859187-35abd388-6178-11e7-8903-3264e1440cc7.png)


[Assembly-CSharp.dll.zip](https://github.com/yangyuan/hearthrock/files/1124206/Assembly-CSharp.dll.zip)

**Comment by yangyuan** [comment]
@jakibaki OMG Blizzard must be kidding me.
It's not encrypted LOL.
Not sure if unencrypted version can be used on Windows, I will test it soon.

**Comment by yangyuan** [comment]
Update: Mac version of Assembly-CSharp.dll does work on Windows.
They reference different native DLLs.

Trying alternative solutions.

**Comment by yangyuan** [comment]
I think it might be blowfish.
First, it supports 64 bits block.
Second, it supports up to 0x38 bytes key... exactly the length of the extra block in the end of the file.

I noticed hearthstone.exe embedded the OpenSSL static lib, so probably they are using an encryption available in OpenSSL, and blowfish is there.

I'm setting up an environment to test this hypothesis...

**Comment by AiSatan** [comment]
ok, I tried use Api Monitor, but I saw only this, maybe it is can give some help for us

![image](https://user-images.githubusercontent.com/2905049/27952450-fb870a8e-6310-11e7-86e4-16c4c8900356.png)

**Comment by yangyuan** [comment]
@AiSatan  For ApiMonitor, I think it can only hook known WIN32 and COM APIs.

I just verified yesterday, IT IS blowfish.
I've updated the NuGet package and working on the code.

**Comment by Velho** [comment]
It doesn't matter for Hearthrock even if the assembly is encrypted, only it cares when is decrypted at runtime?

**Comment by z7oka** [comment]
Hi,
How do you provide an unencrypted version of Assembly-csharp.dll in your binary?
Do you use an external tool to do that before packing or is it done somewhere in your code ?
Thanks

**Comment by yangyuan** [comment]
@z7oka as we discussed in this post, the dll was encrypted with blowfish.
I wrote a small tool to decrypt the dll, but because of some license conflicts, I cannot include that in this repo.

If they do not change the encrypting method, I will re-write the decrypting tool and publish it in this repo.

**Comment by z7oka** [comment]
Thanks @yangyuan for the quick response. 
So if I try to code a similar tool; Using the key - last 56 bytes - in the dll. Should I decrypt the full dll or some portions? I remember you mentioned text (assembly) data is what is encrypted, does this still hold? And the PE signature is modified too, did you mean its part of the encrypted data as well?

**Comment by yangyuan** [comment]
@z7oka 
I shared a gist which contains my code but doesn't contain the third-party code.
https://gist.github.com/yangyuan/14444ccbc08517f64b31cf24165fccf2
This could be better than my explanation.

**Comment by z7oka** [comment]
Thank you so much!

**Comment by vietnguyen09** [comment]
Sorry for asking for help with my problem on this topic, but is your case like mine? I'm getting Assembly-CSharp.dll with a weird obfuscator. I don't know it is the same as yours?

![image](https://user-images.githubusercontent.com/4090897/134754658-8d62af96-ba2b-4d5f-b15b-792c1eff2cc2.png)

Thanks for help,

**Comment by bionemis** [comment]
> @z7oka ho condiviso un assaggio che contiene il mio codice ma non contiene il codice di terze parti. https://gist.github.com/yangyuan/14444ccbc08517f64b31cf24165fccf2 Questo potrebbe essere migliore della mia spiegazione.

Hi yangyuan how i can compile this?
