### ISSUE TITLE
Suggestion: Add more data to scene

### ISSUE THREAD

**Issue by Evanito** [yangyuan/hearthrock#19]
I would find helpful:
- Max resources
- Turn number
EDIT:
- Current deck code/id? (For identifying decks from each other within the code)

**Comment by yangyuan** [comment]
I will take a look whether they are available in game states.
If yes, I will include them in next release.

**Comment by yangyuan** [comment]
Max resources and turn number has been added #21.
About deck id or cards in the deck... so far I haven't found a way to get them from GameState.
