### ISSUE TITLE
Very nice, could you update it to support 2.7.0?

### ISSUE THREAD

**Issue by nuqiewuoz** [yangyuan/hearthrock#2]
I tried it on 2.5.0, it works well.
Could you update it for 2.7.0?

**Comment by yangyuan** [comment]
I will try, but not recently. Busy with something else, sorry.

**Comment by yangyuan** [comment]
I tested the current version, I works on ranked mode.
Which mode is not working?

**Comment by nuqiewuoz** [comment]
The practise mode(PVE, both normal or hard) is not worked.
And the new mode --Tavern Brawl, doesn't have entrance.

**Comment by yangyuan** [comment]
clean old issues.
