### ISSUE TITLE
VS Debugging

### ISSUE THREAD

**Issue by odkken** [yangyuan/hearthrock#23]
What is the correct way to attach VS's debugger?  Is there a way to run without patching the client?

So far I've tried patching the client, then attaching VS to the Hearthstone process, but Hearthstone crashes when I do this.

**Comment by yangyuan** [comment]
What u want to "debug"?
Hearthstone, Hearthrock or your bot?

If you want to debug ur bot, it's better to use client-server (remote bot) mode and debug your own process.
There are python, nodejs examples of bot. If you want to use C#, OWIN would be a great choice.

**Comment by odkken** [comment]
Want to debug Hearthrock & bot (c#).  I'm interested in stepping through & learning how Hearhthrock achieves interactivity, as well as being able to debug my custom bot code.  Was hoping they could both be done in VS, same process, but it seems that may not be the case.

How do you debug (Hearthrock for instance)?

**Comment by yangyuan** [comment]
Logging/tracing should be sufficient.

If you really want to use debugging features, you might want to check some Mono/Unity tools.
