### ISSUE TITLE
Not issuing requests to remote server?

### ISSUE THREAD

**Issue by RandomSeeded** [yangyuan/hearthrock#24]
Thanks for your work, really excited to try working with this.

Not used to developing on Windows, so was going to attempt to run against a remote server where I would do development. Remote bot server is running on port 7625, and is capable of receiving requests. I've used ngrok to create a tunnel.

If I curl http://[my ngrok url]:80, I will get the response 'Hearthstone!'

However, when attempting to run hearthrock against that url as follows, no requests are made to my server.

![capture](https://user-images.githubusercontent.com/12238421/29482815-b0c76508-844d-11e7-89e0-592eec613a2f.PNG)

Is remote currently supported? Anything I'm clearly doing wrong?

--

Edit: have also tried running that server without a tunnel and port forwarding, still no requests made.

**Comment by AiSatan** [comment]
did you try add "/" ?

like:

http://[my ngrok url]:80/

**Comment by RandomSeeded** [comment]
Hah the `/` did it. I really appreciate your getting back to me so quickly :)

**Comment by yangyuan** [comment]
#25 **Add a small validation on BotEndpoint config.**
XD
