### ISSUE TITLE
无法从 .product.db  读取正确的版本号，无法进行注入

### ISSUE THREAD

**Issue by zoumorn** [yangyuan/hearthrock#27]
上一个版本期待的正确返回值是：9.0.0.20457，但我这里返回的是一串16进制字符串。
当前版本 9.1.0.20970，我这里返回的是 "last"。

代码： Patcher.cs Ln:348 ReadPegasusVersion 的返回有误，是不是对 .product.db 文件的解析还有一些问题？或者干脆跳过版本号比较步骤，因为对需要注入的文件 Assembly-CSharp.dll 已经进行了 sha1 比较。

另外：能否将  Assembly-CSharp.dll 解密的代码集成到项目中，或者公布一下？谢谢

**Comment by yangyuan** [comment]
About decrypting, it is blowfish, and plz referrer here: #13

**Comment by yangyuan** [comment]
about .product.db, can u share ur .product.db example, and also environment infomation.

**Comment by yangyuan** [comment]
And also plz use English so other ppl can also help while I am busy with course work.

**Comment by zoumorn** [comment]
抱歉我的英文几乎无法正常书写。

我今天尝试了按 issue #13 能成功解密, 几点笔记：
pe 文件的头部未加密，加密数据以 image section headers 后面为起点
key 在文件最后，包含了一个字节 0x38 长度和另外四个字节的0001

**Comment by zoumorn** [comment]
Windows 10, hearthstone version: 9.1.0.20970

[product.zip](https://github.com/yangyuan/hearthrock/files/1323384/product.zip)

I don't have the old version of .product.db,  version was updated. The old version .product.db (9.0.0.20457) returns a hex string like "34f908d8832480980193801284"

**Comment by sakuratyan** [comment]
留名

**Comment by yangyuan** [comment]
Fixed on 0294dfa3e7509da8fac85e41b8a43ba6b641a58d
