### ISSUE TITLE
使用 IronPython 实现动态修改内置bot的逻辑

### ISSUE THREAD

**Issue by zoumorn** [yangyuan/hearthrock#28]
希望能够使用动态修改的方式实现内部bot的逻辑，这样不需要每次升级ai后都更新版本，甚至可以为这些逻辑建立一个库，大家来更新。

实现IronPython无论是使用作为.net与脚本语言python之间的桥梁，不需要对类进行任何包装了。

**Comment by yangyuan** [comment]
To make our project lives longer, we are not going to include any AI (AKA bot logic) in this project.
This project is nothing but a tool to enable u to do AI research on Hearthstone.

Hearthrock has "remote bot" mode thus u can write your code in any language u like.
In that way, U can change ur bot's code without restart or repatch the game client.

**Comment by zoumorn** [comment]
我是看到你主页上的文章实现这个ai过程中有想过用脚本。目前版本的框架是非常优秀的。
