### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by JonNielsen** [yangyuan/hearthrock#29]
Hi guys,

Could you create a small wiki explaining the overall details:

1) The actions (returned by the bot) is an array of integers, but what does those ints represent?

2) Is the bot only asked once for actions, or multiple times per turn?

**Comment by AiSatan** [comment]
1. Please look it this example:
https://github.com/yangyuan/hearthrock/blob/master/src/Hearthrock.Bot/Score/PlayActionScore.cs

`
sceneContext.IsFriendlyCard(playAction[0]) // playAction -  The actions (returned by the bot)
`

Also I shared a class for example: https://github.com/yangyuan/hearthrock/issues/18

2. mutliple times per turn, you can return null for skip turn
