### ISSUE TITLE
Where is hearthrock.json?

### ISSUE THREAD

**Issue by SethKitchen** [yangyuan/hearthrock#3]
In the Patcher in function ReadConfiguration, it is looking for hearthrock.json , but it was never created by the program. I tried making a blank file with the name "hearthrock.json", but then in ReadConfiguration it breaks.

**Comment by SethKitchen** [comment]
Patch Helper Line 230 add  
            
            if (!File.Exists(hearthstoneConfigurationPath))
            {
                WriteConfiguration(root, new RockConfiguration());
            }

I hope you will add documentation on how to use. I load up the screen and pick the random example bot and press sync, but nothing happens. I press Patch, nothing happens

**Comment by SethKitchen** [comment]
I build the Hearthrock .dll and paste it into a Unity project asset folder. I add the script to an empty game object, and run it after I've created a hearthrockconfig file. I get an assembly reference error:

FileNotFoundException: Could not load file or assembly 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Hearthrock.Engine.RockEngine.Reload () (at D:/hearthbot/hearthrock-master/src/Hearthrock/Engine/RockEngine.cs:93)
Hearthrock.Engine.RockEngine..ctor () (at D:/hearthbot/hearthrock-master/src/Hearthrock/Engine/RockEngine.cs:50)
Hearthrock.Unity.RockUnity..ctor () (at D:/hearthbot/hearthrock-master/src/Hearthrock/Unity/RockUnity.cs:25)

**Comment by yangyuan** [comment]
Your are not supposed to manually copy paste the Hearthrock.dll to anywhere, you should use Hearthrock.Client to inject Hearthrock into your healthstone client.

It seems that Hearthrock.Client cannot find your hearthstone path.
Check PatchHelper.SearchHearthstoneDirectory() method, I think you can quickly fix it.

Sorry for the inconvenience, I spent some time on the bot logic, I will come back and make Hearthrock.Client more stable.
