### ISSUE TITLE
The "whats new tutorial" issue for 9.4.0.22115

### ISSUE THREAD

**Issue by yangyuan** [yangyuan/hearthrock#31]
I tried to update Hearthrock for 9.4.0.22115 a few days ago.
I found an issue that if I run Hearthstone with Hearthrock, the game client will ALWAYS enter "whats new tutorial". Worsely, I cannot click the button for starting the tutorial.

I didn't get time to check the root of the cause carefully. But a quick glance tells me that they have some unsafe codes for the "whats new tutorial". They probably will improve the code and the problem will be solved.

So I decided to publish a new version without solving this issue. I will keep an eye on this to determine whether or not we should solve the problem on our side.

Right now, if you stuck inside the "whats new tutorial". You can simply click run/pause button of Hearthrock, and Hearthrock will help you to get out of "whats new tutorial".

**Comment by AiSatan** [comment]
I am not sure why I see only black screen with rock menu in the top, if I click start I see "Rock started" but it is all

**Comment by yangyuan** [comment]
Hmm, so the problem is more serious than I thought.

I don't have time to do deep analyze recently, but I noticed that they added more prioritized dialog, and also modified the priorities of input layers.

But none of those change can cause a black screen, there must be some errors.
You can check Hearthstone_Data\output_log.txt to see if there are some hints.

**Comment by AiSatan** [comment]
I see a strange message there:

`The file 'F:/Hearthstone/Hearthstone_Data/level0' is corrupted! Remove it and launch unity again!
[Position out of bounds!]`

Any idea?
I try on Windows 10 x86

[output_log.txt](https://github.com/yangyuan/hearthrock/files/1485412/output_log.txt)

**Comment by yangyuan** [comment]
Have you tried to repair the Hearthstone client? It looks like one resource file is damaged.
I don't think this error it's related to Hearthrock.

**Comment by AiSatan** [comment]
yes, and it is work fine if I click "recovery"
I will check it in second PC
Anyway, it is offtop here

**Comment by AiSatan** [comment]
Well, work fine in the second PC, I will look the tutorial issue too

**Comment by yangyuan** [comment]
Update, this issue is related to Encryption and Decryption, need more investigation.

**Comment by yangyuan** [comment]
```
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Spent 0.2459452s so far reading Data/win/rad_enus.unity3d..
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Spent 0.5197854s total time reading RuntimeAssetDatabase
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Failed setting triangles. Some indices are referencing out of bounds vertices. IndexCount: 6, VertexCount: 4
 
(Filename:  Line: 1114)

FSM not Preprocessed: DrawerClose : FSM
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

FSM not Preprocessed: DiskLoading : FSM
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

FSM not Preprocessed: DiskMainMenu : FSM
```

When I use decrypted dll I can get this error.

```
Failed setting triangles. Some indices are referencing out of bounds vertices. IndexCount: 6, VertexCount: 4
 
(Filename:  Line: 1114)
``

**Comment by mcheng916** [comment]
hi, while it works okay sometimes for the first game.
After the first game, it gets stuck in "whats new tutorial"
Is this a known issue?

**Comment by zoumorn** [comment]
Have you ever tried to encrypt the Assembly-CSharp.dll with the same key after you hooked?

**Comment by mcheng916** [comment]
hi, zoumorn, thanks for the response.
Im not familiar with encryption of the dll file, mind if sharing an example? a link in either english or chinese is fine... thanks in advance

**Comment by michaelpittino** [comment]
https://gist.github.com/yangyuan/14444ccbc08517f64b31cf24165fccf2

**Comment by michaelpittino** [comment]
Found a simple workaround. Install hook inside the the unencrypted `Assembly-CSharp-firstpass.dll`. :b

**Comment by michaelpittino** [comment]
So forget my last comment, I saw that the `Assembly-CSharp.dll` hook is necessary for the input manager.

I built a little tool that encrypts the modified `Assembly-CSharp.dll` again but apparently the "whats new tutorial" issue isn't related to encryption, since it appears even with the encrypted assembly.

I've attached the encrypted assembly so you can test it yourself.

[Assembly-CSharp.zip](https://github.com/yangyuan/hearthrock/files/1589443/Assembly-CSharp.zip)

**Comment by jaime** [comment]
> And btw, while doing a little research I think the file responsible for decrypting the assembly is the Hearthstone_Data\Plugins\MemModule32.dll file.

That makes sense because this is the error I found in my HS log

`Error.AddDevFatal() - message=MemModule: Failed to validate signature for: "Hearthstone_Data/Plugins/MemModule32.dll"!
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)`

And BTW, if I log with my iPad after patching the PC, "whats new" appears as well so I can say its more an account wide problem.

**Comment by AiSatan** [comment]
Did you try this comment above?

> Have you ever tried to encrypt the Assembly-CSharp.dll with the same key after you hooked?

**Comment by michaelpittino** [comment]
This is what I've done..

**Comment by AiSatan** [comment]
> I've attached the encrypted assembly so you can test it yourself.

I thought it's decrypted assembly?
if it same assembly with hook.. I do not see rockUI here

I mean,
decrypt current assembly(I mean original HS asm), then set rock-hook, and then encrypt it again

**Comment by michaelpittino** [comment]
> decrypt current assembly(I mean original HS asm), then set rock-hook, and then encrypt it again

Yes, this is exactly what the uploaded assembly is.

**Comment by AiSatan** [comment]
So, it's strange, because I do not see rock ui, 
I can patch the asm and I see that the asm size changed to 7,139 from 7,102 (original asm size 7,103), and rock ui here
just the uploaded asm behavior just like decrypted version

**Comment by michaelpittino** [comment]
It's working for me: https://i.imgur.com/3sK5c6r.jpg

Here are the steps what I've done:

1. Make sure your `Managed_Data` folder is clean: original `Assembly-CSharp.dll`, no `Hearthrock.dll` and `heartrock.json`.
2. Patch `Assembly-CSharp.dll` using the hearthrock Client.
3. Replace `Assembly-CSharp.dll` with my encrypted `Assembly-CSharp.dll`.

But as you can see on the screenshot, the "whats new tutorial" problem still persists.

**Comment by michaelpittino** [comment]
Oh, seems like it works in some way now. Haven't changed anything but, hearthrock somehow glitched into  the practice mode: https://i.imgur.com/cN7peiR.jpg

**Comment by AiSatan** [comment]
Ok, thanks, let me check this steps later

Yes, rock can ignore all and run selected mode, but it's not very helpful.. 

Yes, it's discover issue

**Comment by michaelpittino** [comment]
But there still seems to be an input problem when you glitch into a game - you can't click any menu buttons like friends list or the bottom right menu button.

**Comment by zoumorn** [comment]
Hi @mcheng916 and all: 

Here is my decryption of Assembly-CSharp.dll:

[Decrypt the Assembly-CSharp.dll in hearthstone windows client](https://gist.github.com/zoumorn/24f30bf4fb22744f589075f6355549f0)
depends on blowfish alg:
[blowfish.zip](https://github.com/yangyuan/hearthrock/files/1590243/blowfish.zip)

I don't have much time to encrypt the DLL back and test it, you guys can try.
I am not good at Unity3D programming, I was thinking if we just inject an empty function call in the DLL and encrypt it back, then what will happen?  The problem could be the input hooking.

**Comment by michaelpittino** [comment]
Is there something different in your decryption method. Cause we already've done that..

**Comment by zoumorn** [comment]
Just another implementation for your information, the function are same.

**Comment by yangyuan** [comment]
Ahh...

First I call this "whats new tutorial" issue, but after some investigation, I realize the problem is not related to that tutorial.
Many top-level UI components have problems.
For example, you can't click"option" button (like @michaelpittino said).
The text is missing in "your turn" message box. etc.

If you click "run" button on hearthrock, hearthrock will bring you to practice mode (or other mode depends on your configuration).

I tried to...
1. Decrypt Assembly-CSharp.dll, don't do any hook. Problem persists.
So I was convinced that the problem is not caused by the hook of InputManager or the injecting of hearthrock.

2. Decrypt Assembly-CSharp.dll, then encrypt back, which can generate exactly same Assembly-CSharp.dll
Problem is gone.
So encryption/decryption algorithm/implementation should be okay, huh.

**Comment by AiSatan** [comment]
I tried Decrypt, then hook, then Encrypt again, and then I tried Decrypt again, but got exception 

![image](https://user-images.githubusercontent.com/2905049/34406289-22c8d276-ebc9-11e7-8776-82c27787a397.png)

**Comment by michaelpittino** [comment]
> Decrypt Assembly-CSharp.dll, then encrypt back, which can generate exactly same Assembly-CSharp.dll
Problem is gone.
So encryption/decryption algorithm/implementation should be okay, huh.

Do you mean by that, that the "whats new tutorial" doesn't appear?
If so, do you use a different encryption algorithm than I do? (https://gist.github.com/michaelpittino/0cde9ae55c10714dfe11186e7183ea0f)

> I tried Decrypt, then hook, then Encrypt again, and then I tried Decrypt again, but got exception

I think hooking alters some of the PE information and the start of the .text section - which is why you get that error.

**Comment by AiSatan** [comment]
> If so, do you use a different encryption algorithm than I do? 

I am using your algorithm and hs work fine with it, if I do not set the hook

> I think hooking alters some of the PE information and the start of the .text section - which is why you get that error.

So, if HS got same error probably it is the reason why we got  the "whats new tutorial"

**Comment by michaelpittino** [comment]
> So, if HS got same error probably it is the reason why we got the "whats new tutorial"

Maybe, but it shouldn't. The file isn't corrupt or anything - just some values of the PE header changed, and the section size, which gave it a new start address. Hearthstone *shouldn't* care about that. I could be wrong tho.

**Comment by yangyuan** [comment]
> I tried Decrypt, then hook, then Encrypt again, and then I tried Decrypt again, but got exception
So you are using the previews code I shared.
That code is hard-coded for original DLL, after "hook", the PE header of DLL has been modified thus original decrypt code cannot work on that.

**Comment by yangyuan** [comment]
@michaelpittino 
My code was in here, https://gist.github.com/yangyuan/14444ccbc08517f64b31cf24165fccf2
Basically the same logic as your code. I tried to extract header info so that I can detect header size, but I lost the patient.

We use the same BlowFish implementation.

**Comment by michaelpittino** [comment]
> Second,
Just decrypt Assembly-CSharp.dll, don't do any hook. Problem persists.

What if there is still something wrong with the decryption? Apparently Heartsthone should work with unencrypted assemblies too - since they use the same Unity Build for PC, Mac and Android - and only the PC uses an encrypted assembly.

Could someone upload the assembly from the Mac version? So we could compare it with our decrypted assembly.

**Comment by yangyuan** [comment]
> Could someone upload the assembly from the Mac version? So we could compare it with our decrypted assembly.

@michaelpittino 

- PE headers will be different, that's for sure.
- Text section is actually some binary tables. If decryption is wrong, then assembly should not even runnable.
- I compared the decrypted DLL with the unencrypted DLL in earlier versions, it looks okay.

But it would be good if someone could share it so that we can be confident about decryption.

**Comment by michaelpittino** [comment]
What if there's something else to do besides just decrypting the sections? Do you know what the 5 bytes after the key in the encrypted assembly mean?

**Comment by yangyuan** [comment]
@michaelpittino 
I think the last 1 byte is the number of sections, and the remaining 4 bytes are the size of the key.
It is a typical binary format design.

**Comment by AiSatan** [comment]
@yangyuan 

I heard Mono.Cecil broke a strong name, can it be somehow depended?

I wrote this code and problem persists.

``

        public static void Inject()
        {
            var hearthstoneAssemblyPath = Path.Combine(HSDecPath);

            var resolver = new DefaultAssemblyResolver();
            resolver.AddSearchDirectory(Path.Combine(OriginalPathToGame, "Hearthstone_Data\\Managed\\"));

            var hearthstoneAssembly = AssemblyDefinition.ReadAssembly(hearthstoneAssemblyPath,
                new ReaderParameters { AssemblyResolver = resolver });

            var tmpAssembly = AssemblyDefinition.ReadAssembly(hearthstoneAssemblyPath,
                    new ReaderParameters {AssemblyResolver = resolver});

            var writeLineMethod = typeof(Console).GetMethod("WriteLine", new Type[] { typeof(string) });
            var writeLineRef = tmpAssembly.MainModule.Import(writeLineMethod);

            var methodSceneMgrStart = hearthstoneAssembly.GetMethod("SceneMgr", "Start");
            methodSceneMgrStart.Body.Instructions.Insert(0, Instruction.Create(OpCodes.Ldstr, "Inject!")); 
            methodSceneMgrStart.Body.Instructions.Insert(1, Instruction.Create(OpCodes.Call, writeLineRef));
            tmpAssembly.Write(OriginalPath);
        }

**Comment by yangyuan** [comment]
@AiSatan 
I didn't notice Mono.Cecil breaks any strong name.

And also, I don't think Mono.Cecil plays a role in this issue. The size is larger because the DLL generated by Mono.Cecil has different PE structure, which should be fine.

**Comment by michaelpittino** [comment]
It would be interesting to find out how the "whats new" tutorial gets triggered.
I just can't find a relationship of the "whats new" tutorial with the assembly.

It's even more interesting that apparently the state gets saved server side, since the issue can be observed on other devices too when triggered by the modified assembly.

**Comment by benkio** [comment]
Here I have a very similar situation, but now with the "what's new" tutorial but with the year of mammuth rotation, at some point I cannot click the "next" button to return to the main menú.

**Comment by michaelpittino** [comment]
This is the issue we are talking about.

**Comment by AiSatan** [comment]
I found one modified dll that works fine, try it please, maybe it'll be helpful for us, I don't know

this lib description (sorry it's just google translate):

triple acceleration of some animations
removed the effect of shaking
the time limit for using emotions is disabled
added the opportunity to receive gifts for the GalaxyGift promotion
forced use of the Blizzard store (useful when using a mobile interface)
All missing maps in the collection are displayed in color
The cards are deployed in the opponent's hand in spectator mode for two players


[Hearthstone+PC+v10.0+MixMod.zip](https://github.com/yangyuan/hearthrock/files/1695072/Hearthstone.PC.v10.0.MixMod.zip)

**Comment by AiSatan** [comment]
Well, I've patched the assembly with Rock, and now it's both work fine, you can test with this:

[Assembly-CSharp.zip](https://github.com/yangyuan/hearthrock/files/1695134/Assembly-CSharp.zip)

**Comment by yangyuan** [comment]
@AiSatan Thanks for providing this, it is very fun. I will take a look and compare the difference.
Can you share the website you find download? I guess hearthstone will update very soon...

**Comment by AiSatan** [comment]
I'm afraid that this site will not help, it's like all mods in one forum thread and it's Russian, something like xda for mobiles:

> Windows: MixMod с GalaxyGift

[https://4pda.ru/forum/index.php?showtopic=870696](https://4pda.ru/forum/index.php?showtopic=870696)


Also I saw it here:

[https://w3bsit3-dns.com/forum/index.php?showtopic=870696](https://w3bsit3-dns.com/forum/index.php?showtopic=870696)

**Comment by AiSatan** [comment]
Great news!
I've talked with developer the library: (google translate from Russian)

> Greetings!
Yes, I saw Hearthrock. Funny thing. ;)
What about the library: why do you encrypt it after making changes, do you have the same project? You can leave it in a normal state.
I deconstruct the decoded library from the memory of the game. Simply I cut off the necessary piece of memory, and I save to disk.
This can be done in HEXWorkShop, or in any other hex editor working with memory.
And the modification of the library I make through
https://github.com/0xd4d/dnSpy

Well, after that, I tried by myself, with mine HexEditor https://mh-nexus.de/en/downloads.php?product=HxD

I found the lib in memory. I found the lib's end (12db551F in my case) and move up to 6EF500 and found start's section. then I saved it as * .cs and then save as * .dll

I tried to run - all fine,
and then I patch it, and all works fine

I attached original (from memory)
and patched version as well
[Original from memory with cs files.zip](https://github.com/yangyuan/hearthrock/files/1698433/Original.from.memory.with.cs.files.zip)
[Assembly-CSharp-patched.zip](https://github.com/yangyuan/hearthrock/files/1698437/Assembly-CSharp-patched.zip)

**Comment by yangyuan** [comment]
@AiSatan Great job.

The Assembly-CSharp.dll in Hearthstone+PC+v10.0+MixMod.zip has some corrupted data in the header. (To be specific, in optional PE header)
The Assembly-CSharp.dll you provided has malformed data between 0x200 to 0x400. Which also falls in the range of optional PE header.

The original Assembly-CSharp.dll actually doesn't encrypt the data between 0x200 to 0x400. and it contains the information of reloc section.

So I suspect that there are some data in optional PE header which brings the trouble. The hearthstone corrupt that data during decryption.

**Comment by yangyuan** [comment]
@AiSatan 
They just updated the client to 10.2. I use the Hexden to check the decompiled dll in the memory, it looks like they have fixed the issue (malformed data between 0x200 to 0x400). Instead, they choose not to decompile the data between 0x700200 and 0x700C00, which belongs to .sdata section.

I think they have improved their decrypt code. I tried to do that same thing in my decryption code (ignore .sdata) and it works.

I will update hearthrock as long as the Nuget package today. Thank you very much for your help.

**Comment by AiSatan** [comment]
@yangyuan 
I'm glad to help :)

So... We did it! :) 🔢 🥇 👍

**Comment by malvarezcastillo** [comment]
Probably not what this issue is for, but how did you exactly fix this issue?

I'm decrypting the dll using https://gist.github.com/judge2020/117532eb7084708aa56919324133fd93 and I'm stuck at the Year of the Raven "tutorial" and I can't advance. What do I have to fix in the decrypted .dll to be able to click?
