### ISSUE TITLE
Help with patching the Client.

### ISSUE THREAD

**Issue by XCGGV** [yangyuan/hearthrock#39]
I cant really Figure out how to run the Hearthrock.Client to Patch my Hearthstone. Sorry to bother you with that basic stuff.

**Comment by Evanito** [comment]
I don't think the bot (releases) is updated to support the most recent version :(

**Comment by Evanito** [comment]
If @yangyuan would build and release the most recent version that would be great!

**Comment by michaelpittino** [comment]
Well, it wouldn't work anyway. See: https://github.com/yangyuan/hearthrock/issues/31

**Comment by yangyuan** [comment]
@Evanito hahaha sry I forgot to publish the binaries... hahaha
