### ISSUE TITLE
Bot missing lethal, or Kill Command/Quick Shot your own face

### ISSUE THREAD

**Issue by maniek093** [yangyuan/hearthrock#42]
Can we make so bot always uses damaging spells on enemy face ? I play only Face Hunter so more complicated things like spells healing yourself doesn't matter.

Also, bot constantly misses lethal and makes questionable trades. How can I change the code to make the bot more consistent ?

**Comment by yangyuan** [comment]
Hi @maniek093 
I'm very sorry but I'm going to close this issue.

This project is an engine to build your own bot. We only provide a default bot which does random actions.
For a long-term perspective, we don't want to challenge the bottom line of Blizzard. So we don't (at least not officially) provide the support of strategies of bots.
