### ISSUE TITLE
New Version

### ISSUE THREAD

**Issue by AiSatan** [yangyuan/hearthrock#54]
I think, we have to decide how we will up-to-date, because we can't always interrupt you from work.

This is a new patched version, you should backup your files and just replace them
[Assembly-patched.zip](https://github.com/yangyuan/hearthrock/files/1898270/Assembly-patched.zip)

Please, not remove your own hearthrock.json, I've not added it to the zip, you should use your own

**Comment by xlemmingx** [comment]
Sorry for the question, but can I somehow update for myself? I just recently discovered this project and would really like to play around a bit with it the next days, but the client doesn't patch because of the version mismatch.

**Comment by AiSatan** [comment]
standard hs assembly encrypted, you can use this assembly, it's not patched, but decrypted
or search with any hex editor in memory for this assembly (more info here #31) 

[Assembly-CSharp.zip](https://github.com/yangyuan/hearthrock/files/1914576/Assembly-CSharp.zip)


you should replace all asm with the same name in this project (in package folder, bin folder, etc.)
then remove all checksum and version check from project, so you will can patch this asssembly

**Comment by alanbaumgartner** [comment]
@AiSatan In reference to the issue you linked, how do you find the start/end section? Just searching for the string "Assembly-CSharp.dll" I found something but I am completely unfamiliar with using hexeditors or anything related to this.

**Comment by AiSatan** [comment]
@ala

**Comment by AiSatan** [comment]
Sorry, miss click :D

Hi, 

In hex editor you should open assembly-csharp (original from hs folder) and open hs ram

And search in hs ram something familiar with assembly-csharp 

I'm usually search assembly-csharp end sections in hs ram, than search back for start section, than just right click - select block - write start point, and end point, copy selected 
File-new-paste

**Comment by AiSatan** [comment]
I add some screenshots, I am not do exactly this steps, but I hope it's add some sense

I hope blizz not ban for this,
if @yangyuan think it harmful, I will remove this message

![image](https://user-images.githubusercontent.com/2905049/39041996-817fdd88-4492-11e8-89ad-ff8cc99f4103.png)

![image](https://user-images.githubusercontent.com/2905049/39042056-a15f8bbc-4492-11e8-952c-a54bd436315b.png)

![image](https://user-images.githubusercontent.com/2905049/39042084-af731ab6-4492-11e8-948a-103dfd0e6aaf.png)

![image](https://user-images.githubusercontent.com/2905049/39042179-dec1ebf8-4492-11e8-809e-faf856ca0ab7.png)

![image](https://user-images.githubusercontent.com/2905049/39042233-faff68d6-4492-11e8-9e08-c1cc3d561dcd.png)

![image](https://user-images.githubusercontent.com/2905049/39042272-133fba36-4493-11e8-8dc6-36b5b5d73f70.png)

![image](https://user-images.githubusercontent.com/2905049/39042305-28893a48-4493-11e8-8ad8-dd523887803e.png)


![image](https://user-images.githubusercontent.com/2905049/39042731-3be26a64-4494-11e8-8ffb-62a3fb5f8bc0.png)




![image](https://user-images.githubusercontent.com/2905049/39042608-f2af0ffa-4493-11e8-806f-0f3270d11421.png)

**Comment by alanbaumgartner** [comment]
@AiSatan thanks for the post! I did figure it out without the photos so feel free to delete them if you think it will be harmful to have them up.

However, when I try to patch hearthstone, I always end up corrupting the game files. I commented out the version checking from Patcher.cs and pasted the Asssembly-CSharp.dll.

Maybe I am still too new to this and need to study more...

**Comment by AiSatan** [comment]
@alanbaumgartner try to replace this files too

from Hearthstone\Hearthstone_Data\Managed to \hearthrock\src\Hearthrock.Client\bin\Debug (and all other folders where it can be, like nuget)

Assembly-CSharp-firstpass.dll 
Assembly-UnityScript.dll
UnityEngine.dll

**Comment by alanbaumgartner** [comment]
Here is what I have done step by step.
1. Clone the repo
2. Built from source
3. manually changed pegasus checksum and hearthstone version (I did this to not mess with source code, checksum is from SHA1 and hearthstone version is from battle.net client.)

From here, what should I be placing where? You have two zip's above, if I didn't want to get the assembly-CSharp.dll myself, where should I be pasting the one you provided?

**Comment by AiSatan** [comment]
first zip file - patched assembly, you can just put all this files to Hearthstone\Hearthstone_Data\Managed and use some hearthrock.json file (if you have no this file in the folder, just run hsrock.client, set hs path, choose game mode and click "sync settings") and you can just run game now

second zip file not patched version, you should replace all files in hs rock folders with this files:

from zip:
Assembly-CSharp.dll

and from game directory:
Assembly-CSharp-firstpass.dll
Assembly-UnityScript.dll
UnityEngine.dll

and than run hsrock.client, set path, click patch, and sync settings - now you can play the game

**Comment by shtnoe** [comment]
it's not work for me. i just put all unzipped files(from Assembly-patched.zip) to Hearthstone\Hearthstone_Data\Managed and hearthrock.json file. when i run game, the heathstone client window show and don't show hearhstone title forever.

**Comment by AiSatan** [comment]
@shtnoe, hi
try to launch multiply time, for me it's happens only first run, then work fine

**Comment by jonln** [comment]
@AiSatan Yeah not working for me either. Could you update the client and let us know?

**Comment by yangyuan** [comment]
#57

**Comment by BryanNoller** [comment]
Would be nice to have the update when your not around, I haven't looked into decrypting the dll yet.
I just recently started messing with this project and haven't been able to test what I've written because another hearthstone update 11.0.0.23966 happen a day or two after you fixed it.
