### ISSUE TITLE
Unsure where to begin

### ISSUE THREAD

**Issue by allenc26** [yangyuan/hearthrock#55]
Hi, I'm creating my first bot as a project and am a bit overwhelmed by the source code. I'm unsure where I should start with the bot. I was guessing that the examples are roughly what my bot would turn out to be, and my bot would just call the Hearthrock parts, but I'm still a bit confused on how to have the bot itself use Hearthrocks functions. I'm not looking for a full guide, don't worry, just a bit of direction is all so I have an idea where I should be looking.

**Comment by yangyuan** [comment]
To write your own bot, you can start form this example:
https://github.com/yangyuan/hearthrock/blob/master/examples/python/bots/bot.py

Just modify do_mulligan and do_play functions. If you know python it's easy to understand that currently the sample do_play just return random actions. Your bot should smartly choose the best one via the information in the scene.

The bots are working as Web services.
