### ISSUE TITLE
GetMininWastedCost param

### ISSUE THREAD

**Issue by BryanNoller** [yangyuan/hearthrock#58]
Am I missing something or is the **RockId** param passed to **GetMininWastedCost** really unused?
https://github.com/yangyuan/hearthrock/blob/c4de31f328e88e5f3ed4007727c148ec2e711940/src/Hearthrock.Bot/Score/RockSceneContext.cs#L55-L76

**Comment by yangyuan** [comment]
Yes, it's totally unused.
That is a part of an unfinished feature. Focusing on other things I didn't finish it. (maybe I should remove it first)

**Comment by BryanNoller** [comment]
ok, was just curious. came across it while porting the c# bot over to python to have a decent base to work with.
