### ISSUE TITLE
How do I get the client to use my custom bot?

### ISSUE THREAD

**Issue by Boths** [yangyuan/hearthrock#67]
I downloaded  hearthrock-0.6.5.zip and the source code from [here](https://github.com/yangyuan/hearthrock/releases). I changed the code in RockBot.cs (hearthrock-0.6.5, src, Hearthrock.Bot) and then clicked patch in the client but it still used the original code. (I changed the mulligan code to throw out card with less than 5 mana but it still threw out >= 4 mana cards). I'm completely new to working with projects so I'd really appreciate it if someone can give a dumbed-down answer as to how I can get a custom-coded bot to work on the client.

**Comment by yangyuan** [comment]
If you use source code, you will have to build a "client" from source code. Do not use the client downloaded (aka hearthrock-0.6.5.zip).


I recommend you to use provided client (aka hearthrock-0.6.5.zip) but write the bot in other languages. (for example python) https://github.com/yangyuan/hearthrock/tree/master/examples/python
And configure client to use end endpoint hosted by python.
