### ISSUE TITLE
HI im new here it cant work now

### ISSUE THREAD

**Issue by miku-Sakura** [yangyuan/hearthrock#71]
hearthstone has updated.so bad.by the way are you chinese?

**Comment by yangyuan** [comment]
Will update it this early week.
yes, I'm Chinese

**Comment by JanMolcik** [comment]
Hello! I would like to ask you about release date of the update. I can't wait to start implementing my own bot. Right now the client is outdated right? I can't get it to work.

**Comment by yangyuan** [comment]
So... err, it's a little bit embarrassing.
When I try to update it last week, I made a silly mistake thus delayed the update....

updated!

**Comment by yangyuan** [comment]
@miku-Sakura 大佬算不上，在小众的几个论坛里浪过，脸被打的啪啪响，所以后来就夹着尾巴做人了。

**Comment by miku-Sakura** [comment]
> @miku-Sakura 大佬算不上，在小众的几个论坛里浪过，脸被打的啪啪响，所以后来就夹着尾巴做人了。

还是很厉害了 我不会搞。。。撤了，只能无脑用hr和hb了...smartbot又太贵了 加油哦

**Comment by zhouzekai** [comment]
@yangyuan 有个想法不知道能不能实现：普通卡中间的图片显示成金卡的动图，或者普通卡直接显示成金卡（人家动效做的那么好，不看看真浪费2333）。看了很多以前的issue，还是没看懂究竟是怎么逆向的。想要实现这样一个功能，是否可以在hearthrock的基础上去做呢？能不能给我指一指方向？

**Comment by OrionChang** [comment]
Just wondering when we're gonna get an update of bot.

**Comment by yangyuan** [comment]
@zhouzekai 理论上可以，至少有两个绝对安全的思路：
1. 篡改资源，替换普通资源为金卡资源。
2. 劫持某些显示相关的函数，篡改卡的ID，改为金卡的ID。

这种功能属于外挂性质，不适合讨论。
你要是自己研究，可以下载 https://www.nuget.org/packages/Hearthrock.Stone，然后使用 Visual Studio 火鹤 ILSpy 去研究源码。

**Comment by yangyuan** [comment]
@OrionChang I just updated it. :)
