### ISSUE TITLE
PLS Help with the Programm

### ISSUE THREAD

**Issue by eshatkeinensinn** [yangyuan/hearthrock#73]
Hi 
iam new to github and dont know how to start this programm. Would be nice ,if someone could help me.

Jakob

**Comment by lanhin** [comment]
Hi,
Please refer to the Release tab and download the zip file. The latest version is 0.6.8 Alpha (https://github.com/yangyuan/hearthrock/releases/download/0.6.8/hearthrock-0.6.8.zip). Unzip it and run Hearthrock.Client to patch the hearthstone application and then just try as you like. Sadly there's little docs for this repo. I think you may need some programming experience to make more comprehension.

Unfortunately, 0.6.8 is out of date. I'm just waiting for @yangyuan to publish a new version.

**Comment by yangyuan** [comment]
Thank you @lanhin

BTW, I've updated the project.
