### ISSUE TITLE
Yet another new version =)

### ISSUE THREAD

**Issue by Stektsnus** [yangyuan/hearthrock#76]
Hi yangyuan!

The current Hearthrock version is not up to date with the latest Hearthstone version. I lack the knowledge of updating the Hearthrock version myself and would greatly appreciate an update!

Cheers and thanks for an awesome work.

**Comment by v-secure** [comment]
Hello,

Although I do not know the project well enough to guarantee that this fix has no weird behaviors, I have been able to successfully patch Hearthstone version **13.0.3.28329** by updating the **pegasus.json** file (found in the release zip [0.6.0](https://github.com/yangyuan/hearthrock/releases/download/0.6.10/hearthrock-0.6.10.zip)) with the following values:

`﻿{
    "checksum": "4137629A103C800246890911106F97412582FE8B",
    "version": "13.0.3.28329"
}`

**Comment by AiSatan** [comment]
you did fine, but you also need this new dlls, I decrypted 'em for you

you can just build client project, go to "~hearthrock\src\Hearthrock.Client\bin\Debug"
and replace with this:

[Dlls.zip](https://github.com/yangyuan/hearthrock/files/2734385/Dlls.zip)

it'll be help until new version hsrock will be delivered

**Comment by Stektsnus** [comment]
@AiSatan @v-secure 
It seems to be working now! Thank you very much for your help guys. =)

**Comment by v-secure** [comment]
@AiSatan thank you for the comprehensive reply :) 
I'll have a go at reading through the engine's source code (to get a better understanding of its capabilities) and keep employment at blizzard as a backup plan :D
