### ISSUE TITLE
此方法是静太AOP改写了炉石Assembly-CSharp.dll文件

### ISSUE THREAD

**Issue by SuperJLive** [yangyuan/hearthrock#78]
有没有动态的方法，在运行之后注入来实现？

**Comment by AiSatan** [comment]
Hi, if you can, please, try to use English, even with Google translate, more people will try to help you.

I'm not get that you want to do, 
to reload bot, you can just click stop/run on game bot menu. 

But you can't patch game while it's running

**Comment by AiSatan** [comment]
Yeah, I got that, but if you're looking for faster answer, I'd good to use both :)

I don't think that it's possible, 'cause .net code not so easy, even unity asked to stop game before changing scripts

https://stackoverflow.com/questions/6671907/possible-modify-loaded-c-sharp-dll

**Comment by yangyuan** [comment]
Thanks @AiSatan
So as I know, it is possible, but it is way too much work to do it.

Once an Assembly got loaded into an AppDomain, it cannot be unload, but it can be overloaded and there are some ways to change code business logics on the fly.
But to do that, the program you need to either hijack the process or modify some binaries, which is not much better than the current approach.
