### ISSUE TITLE
Example of python

### ISSUE THREAD

**Issue by huanged** [yangyuan/hearthrock#81]
Hi,

The given example is quite simple. Is there a more complicated example of Python.
Like how to call the hearthrock api. For example, how to call the api to get the type of the Object from the scene?

Regards

**Comment by yangyuan** [comment]
Hearthrock call the BOT (python), BOT (python) provide APIs.
I believe the sample is pretty straightforward. If you have more questions you can try run the Hearthrock with BOT and print the parameters in the BOT.
